Belt-Reviewer/myServer/apps/login/urls.py
from django.conf.urls import url
from views import *
# from django.contrib import admin

urlpatterns = [
    url(r'^$', index, name = 'index'),
    url(r'^register$', register, name = 'registration'),
    url(r'^success$', success, name = 'success'),
    url(r'^login$', login, name = 'login'),
    url(r'^logout$', logout, name = 'logout')
    # url(r'^admin/', admin.site.urls),
]

Belt-Reviewer/myServer/myServer/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.login.urls', namespace= 'users')),
    url(r'^books/', include('apps.books.urls', namespace='books'))
]

Belt-Reviewer/myServer/apps/login/models.py
from __future__ import unicode_literals
from django.contrib import messages
from django.db import models
import bcrypt
import re
EMAIL_REGEX = re.compile (r'^[a-zA-Z0-9.+_-]+@[a-zA-Z0-9._-]+\.[a-zA-Z]+$')

# Create your models here:
class UserManager(models.Manager):
    def valid_registration(self, user_info, request):
        valid = True
        if not user_info['first_name'].isalpha():
            messages.warning(request, "First name must be all letters!")
            valid = False
        if len(user_info['first_name']) < 2:
            messages.warning(request, "First name must be 2 or more characters long!")
            valid = False
        if not user_info['last_name'].isalpha():
            messages.warning(request, "Last name must be all letters!")
            valid = False
        if len(user_info['last_name']) < 2:
            messages.warning(request, "Last name must be 2 or more characters long!")
            valid = False
        if not EMAIL_REGEX.match(user_info['email_address']):
            messages.warning(request, "Email is not a valid email!")
            valid = False
        if len(user_info['password']) < 7:
            messages.warning(request, "Password is too short!")
            valid = False
        if user_info['password'] != user_info['confirm_password']:
            messages.warning(request, "Passwords do not match!")
            valid = False
        if User.objects.filter(email = user_info['email_address']):
            messages.error(request, "This Email already exists!")
            valid = False
        if valid == True:
            # messages.success(request, "Successful registration, " + user_info['first_name'] + "!")
            hashed = bcrypt.hashpw(user_info['password'].encode(), bcrypt.gensalt())
            User.objects.create(first_name = request.POST['first_name'], last_name = request.POST['last_name'], email = request.POST['email_address'], password = hashed)
        return valid

    def exisiting_user(self, user_info, request):
        valid = True
        if User.objects.filter(email = user_info['email_address']):
            hashed = User.objects.get(email = user_info['email_address']).password
            hashed = hashed.encode('utf-8')
            password = user_info['password']
            password = password.encode('utf-8')
            if bcrypt.hashpw(password, hashed) == hashed:
                # messages.success(request, "Success! Welcome back, " + User.objects.get(email = user_info['email_address']).first_name + "!")
                valid = True
            else:
                messages.warning(request, "Oops! You entered an incorrect password!")
                valid = False
        else:
            messages.warning(request, "Oops! Your email is incorrect!")
            valid = False
        return valid

class User(models.Model):
    first_name = models.CharField(max_length=45)
    last_name = models.CharField(max_length=45)
    email = models.EmailField()
    password = models.CharField(max_length=45)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    UserManager = UserManager()
    objects = models.Manager()

Belt-Reviewer/myServer/apps/login/views.py
from django.shortcuts import render, redirect
from .models import User
from django.contrib import messages
from django.core.urlresolvers import reverse

# Create your views here:
def index(request):
    if 'first_name' not in request.session:
        return render(request, 'login/index.html')
    else:
        return redirect(reverse('books:home'))

def register(request):
    if User.UserManager.valid_registration(request.POST, request):
        valid = True
        user = User.objects.get(email = request.POST['email_address'])
        request.session['first_name'] = user.first_name
        request.session['user_id'] = user.id
        return redirect(reverse('books:home'))
    else:
        valid = False
        return redirect(reverse('users:index'))

def success(request):
    return redirect(request, 'books:home')

def login(request):
    if User.UserManager.exisiting_user(request.POST, request):
        valid = True
        user = User.objects.get(email = request.POST['email_address'])
        request.session['first_name'] = user.first_name
        request.session['email_address'] = user.last_name
        request.session['user_id'] = user.id
        return redirect(reverse('books:home'))
    else:
        valid = False
        return redirect(reverse('users:index'))

def logout(request):
    request.session.clear()
    return redirect(reverse('users:index'))

Belt-Reviewer/myServer/apps/login/templates/login/index.html
<!DOCTYPE html>
<html>
<head>
  <title>Belt Reviewer Assignment</title>
  {% load staticfiles %}
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
  <link rel="stylesheet" href="{% static 'login/css/stylesheet.css' %}">
</head>

<body>
  <div class="container">
    <h1>Welcome!</h1> {% if messages %} {% for message in messages %}
    <div class="alert alert-danger" role="alert">
      {{message}}
    </div>
    {% endfor %} {% endif %}

    <div class="row">
      <div class="col-md-6">

        <form class="" action="{% url 'users:registration' %}" method="POST">
          {% csrf_token %}

          <h2>Register</h2>
          <div class="form-group">
            <label for="first_name">First Name</label>
            <input name="first_name" type="text" class="form-control" id="first_name" placeholder="">
          </div>

          <div class="form-group">
            <label for="last_name">Last Name</label>
            <input name="last_name" type="text" class="form-control" id="last_nameLast" placeholder="">
          </div>

          <div class="form-group">
            <label for="exampleInputEmail1">Email Address</label>
            <input name="email_address" type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
          </div>

          <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input name="password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
          </div>

          <div class="form-group">
            <label for="exampleInputPassword2">Confirm Password</label>
            <input name="confirm_password" type="password" class="form-control" id="exampleInputPassword2" placeholder="Confirm Password">
          </div>
          <br>
          <button type="submit" name="register" class="btn btn-default">Register</button>
        </form>
      </div>

      <div class="col-md-6">

        <form class="" action="{% url 'users:login' %}" method="POST">
          <h2>Login</h2>
          {% csrf_token %}

          <div class="form-group">
            <label for="exampleInputEmail1">Email Address</label>
            <input name="email_address" type="email" class="form-control" id="exampleInputEmail1" placeholder="Email">
          </div>

          <div class="form-group">
            <label for="exampleInputPassword1">Password</label>
            <input name="password" type="password" class="form-control" id="exampleInputPassword1" placeholder="Password">
          </div>

          <button type="submit" name="login" class="btn btn-default">Login</button>
        </form>
      </div>
    </div>

  </div>
</body>

</html>