Belt-Reviewer/myServer/apps/books/urls.py
from django.conf.urls import url
from views import *

urlpatterns = [
    url(r'^$', home, name = "home"),
    url(r'^add_book$', add_book, name="add_book"),
    url(r'^create_review/(?P<id>\d+)$', create_review, name="create_review"),
    url(r'^show/(?P<id>\d+)$', show, name="show"),
    url(r'^user/(?P<id>\d+)$', user, name="user"),
    url(r'^delete/(?P<id>\d+)$', destroy, name="destroy")

]

Belt-Reviewer/myServer/apps/login/urls.py
from django.conf.urls import url
from views import *
# from django.contrib import admin

urlpatterns = [
    url(r'^$', index, name = 'index'),
    url(r'^register$', register, name = 'registration'),
    url(r'^success$', success, name = 'success'),
    url(r'^login$', login, name = 'login'),
    url(r'^logout$', logout, name = 'logout')
    # url(r'^admin/', admin.site.urls),
]

Belt-Reviewer/myServer/myServer/urls.py
from django.conf.urls import url, include

urlpatterns = [
    url(r'^', include('apps.login.urls', namespace= 'users')),
    url(r'^books/', include('apps.books.urls', namespace='books'))
]

Belt-Reviewer/myServer/apps/books/models.py
from __future__ import unicode_literals
from django.db import models
from ..login.models import *

# Create your models here:
class Book(models.Model):
    book_title = models.CharField(max_length=255)
    author = models.CharField(max_length=255)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

class Review(models.Model):
    review = models.TextField(max_length=1000)
    rating = models.IntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at= models.DateTimeField(auto_now=True)
    user= models.ForeignKey(User, related_name="user_reviews")
    book= models.ForeignKey(Book, related_name="book_reviews")

Belt-Reviewer/myServer/apps/books/views.py
from django.shortcuts import render, redirect
from .models import *
from django.db.models import Count
from django.core.urlresolvers import reverse
from django.contrib import messages

# Create your views here:
def home(request):
    if not 'first_name' in request.session:
        return redirect('users:index')
    else:
        reviews = Review.objects.all().order_by('-id')[:3]
        books = Book.objects.all()
        context = {
            'reviews':reviews,
            'books':books
        }
        return render(request, 'books/home.html', context)

def add_book(request):
    if not 'first_name' in request.session:
        return redirect('users:index')
    else:
        if request.method == 'POST':
            author=''
            if len(request.POST['author2'])<1:
                if not Book.objects.filter(author=request.POST['author1']):
                    messages.warning(request, "Please select or add author")
                if Book.objects.get(author=request.POST['author1']):
                    author=request.POST['author1']

            if len(request.POST['author2'])>1:
                author=request.POST['author2']

            if not Book.objects.filter(book_title=request.POST['book_title'], author=author):
                Book.objects.create(book_title=request.POST['book_title'], author=author)
                book = Book.objects.get(book_title=request.POST['book_title'], author=author)
                book.book_reviews.create(review=request.POST['review'], rating = request.POST['rating'], user_id=request.session['user_id'])
                return redirect(reverse('books:show', kwargs={'id':book.id}))

        books=Book.objects.all()
        context={
            'books': books
        }

        return render(request, 'books/add_book.html', context)

def show(request, id):
    if not 'first_name' in request.session:
        return redirect('users:index')
    else:
        book = Book.objects.get(id=id)
        reviews = book.book_reviews.all()
        context = {
            'book': book,
            'reviews':reviews
        }
        return render(request, 'books/book_reviews.html', context)

def create_review(request, id):
    if not 'first_name' in request.session:
        return redirect('users:index')
    else:
        Review.objects.create(review=request.POST['new_review'], rating=request.POST['rating'], book_id=id, user_id=request.session['user_id'])
        return redirect(reverse('books:show', kwargs={'id':id}))

def destroy(request, id):
    if not 'first_name' in request.session:
        return redirect('users:index')
    else:
        Review.objects.get(id=id).delete()
        return redirect(reverse('books:home'))

def user(request, id):
    if not 'first_name' in request.session:
        return redirect('users:index')
    else:
        user = User.objects.get(id=id)
        reviews = user.user_reviews.all()
        total = len(reviews)
        context = {
            'user':user,
            'reviews':reviews,
            'total':total
        }
        return render(request, 'books/user_reviews.html', context)

Belt-Reviewer/myServer/apps/books/templates/books/add_book.html
<!DOCTYPE html>
<html>
  <head>
    <title>Belt Reviewer Assignment</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'books/css/stylesheet.css' %}">
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">

          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Book Review</a>
          </div>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="active"><a href="{% url 'books:home' %}">Home<span class="sr-only">(current)</span></a></li>
              <li><a href="{% url 'books:add_book' %}">Add Book</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'users:logout' %}">Logout</a></li>
            </ul>
          </div>
        </div>
      </nav>

      {% if messages %}
        {% for message in messages %}
          {{message}}
        {% endfor %}
      {% endif %}

      <div class="add-review">
        <h3>Add a New Book Title and a Review <span class="glyphicon glyphicon-book"></span></h3>
        <form class="form-horizontal" action="{% url 'books:add_book' %}" method="post">
          {% csrf_token %}
          <div class="form-group">
            <label for="book_title" class="col-sm-1 control-label">Book Title:</label>
            <div class="col-sm-6">
              <input type="text" name="book_title" class="form-control" placeholder="Book Title">
            </div>
          </div>

          <div class="form-group">
            <label for="author" class="col-sm-1 control-label">Author:</label>
            <div class="col-sm-6">
              <select class="form-control" name="author1">
                <option value="">Choose From The List:</option>
              {% for book in books %}
                <option value="{{book.author}}">{{book.author}}</option>
              {% endfor %}
              </select>
              <input type="text" name="author2" class="form-control" placeholder="Or Add a New Author:">
            </div>
          </div>

          <div class="form-group">
            <label for="review" class="col-sm-1 control-label">Review:</label>
            <div class="col-sm-6">
              <textarea class="form-control" name="review" rows="3" placeholder="Review"></textarea>
            </div>
          </div>

          <div class="form-group">
            <label for="rating" class="col-sm-1 control-label">Rating:</label>
            <div class="col-sm-6">
              <select class="form-control" name="rating">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
              </select>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-1 col-sm-6">
              <button type="submit" class="btn btn-info">Add Book</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </body>
</html>

Belt-Reviewer/myServer/apps/books/templates/books/book_reviews.html
<!DOCTYPE html>
<html>
  <head>
    <title>Book Reviews</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'books/css/stylesheet.css' %}">
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">

          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle Navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Book Review</a>
          </div>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="active"><a href="{% url 'books:home' %}">Home<span class="sr-only">(current)</span></a></li>
              <li><a href="{% url 'books:add_book' %}">Add New Book</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'users:logout' %}">Logout</a></li>
            </ul>
          </div>
        </div>
      </nav>
      {% if messages %}
        {% for message in messages %}
          {{message}}
        {% endfor %}
      {% endif %}

      <div class="wrapper">
        <h2>{{book.book_title}} <span class="glyphicon glyphicon-book"></span></h2>
        <p>Author: {{book.author}} </p>
      </div>

        {% for review in reviews %}
        <div class="review">
          <h4><strong>Rating: </strong>{% for i in 'x'|rjust:review.rating %} <span><i class="fa fa-star-o" aria-hidden="true"></i></span> {% endfor %}</h4>
          <h4><strong><a href="{% url 'books:user' id=review.user.id %}">{{review.user.first_name}}</a> says: </strong>{{review.review}}</h4>
          <h5><em>{{review.created_at}}</em></h5>
          {% if request.session.user_id == review.user.id %}
            <a class="btn btn-danger" href="{% url 'books:destroy' id=review.id %}" role="button">
              Delete <span class="glyphicon glyphicon-trash" aria-hidden="true"></span>
            </a>
          {% endif %}
        </div>
        {% endfor %}

      <div class="add-review">
        <h3>Add Review</h3>
        <form class="form-horizontal" action="{% url 'books:create_review' id=book.id %}" method="post">
          {% csrf_token %}
          <div class="form-group">
            <label for="new_review" class="col-sm-1 control-label">Review</label>
            <div class="col-sm-6">
              <textarea class="form-control" name="new_review" rows="3"></textarea>
            </div>
          </div>

          <div class="form-group">
            <label for="rating" class="col-sm-1 control-label">Rating</label>
            <div class="col-sm-6">
              <select class="form-control" name="rating">
                <option value="1">1</option>
                <option value="2">2</option>
                <option value="3">3</option>
                <option value="4">4</option>
                <option value="5">5</option>
              </select>
            </div>
          </div>

          <div class="form-group">
            <div class="col-sm-offset-1 col-sm-6">
              <button type="submit" class="btn btn-info">Submit Review</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </body>
</html>

Belt-Reviewer/myServer/apps/books/templates/books/home.html
<!DOCTYPE html>
<html>
  <head>
    <title>Belt Reviewer Assignment</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'books/css/stylesheet.css' %}">
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">

          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle Navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Book Review</a>
          </div>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="active"><a href="{% url 'books:home' %}">Home<span class="sr-only">(current)</span></a></li>
              <li><a href="{% url 'books:add_book' %}">Add Book and Review</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'users:logout' %}">Logout</a></li>
            </ul>
          </div>
        </div>
      </nav>

      {% if reviews %}

        <div class="">
          <h1>Welcome, {{request.session.first_name}}!</h1>
          <p>Take a look at the reviews below!</p>
        </div>

        <h3>Recent Book Reviews <span class="glyphicon glyphicon-book"></span></h3>
        {% for review in reviews %}
          <div class="review">
            <h4><strong><a href="{% url 'books:show' id=review.book.id %}">{{review.book.book_title}}</strong></a></h4>
            <h4><strong>Rating: </strong>{% for i in 'x'|rjust:review.rating %} <span><i class="fa fa-star-o" aria-hidden="true"></i></span> {% endfor %}</h4>
            <h4>{{review.user.first_name}} says: {{review.review}}</h4>
            <em><h5>{{review.created_at}}</h5></em>
          </div>
        {% endfor %}

        <h3>Other Books with Reviews <span class="glyphicon glyphicon-book"></span></h3>
        <div class="review">
          {% for book in books %}
          <h4><a href="{% url 'books:show' id=book.id %}">{{book.book_title}}</a></h4>
          {% endfor %}
        </div>

      {% else %}

      <div class="wrapper">
        <h1>Hello, {{request.session.first_name}}!</h1>
        <p>Currently, there are no reviews. Go ahead and add one! </p>
      </div>

      {% endif %}
    </div>
  </body>
</html>

Belt-Reviewer/myServer/apps/books/templates/books/user_reviews.html
<!DOCTYPE html>
<html>
  <head>
    <title>Belt Reviewer Assignment</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'books/css/stylesheet.css' %}">
  </head>
  <body>
    <div class="container">
      <nav class="navbar navbar-default">
        <div class="container-fluid">
          <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
              <span class="sr-only">Toggle Navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">Book Review</a>
          </div>

          <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
              <li class="active"><a href="{% url 'books:home' %}">Home<span class="sr-only">(current)</span></a></li>
              <li><a href="{% url 'books:add_book' %}">Add New Book</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'users:logout' %}">Logout</a></li>
            </ul>
          </div>
        </div>
      </nav>
      <div class="wrapper-info">
        <h3>Name: {{user.first_name}} {{user.last_name}}</h3>
        <p>Email: {{user.email}}</p>
        <p>Total Reviews: {{total}}</p>
        <p class="p-info"><strong>Posted Reviews on the Following Books:</strong></p>
        <ul>
          {% for review in reviews %}
            <h4><li><a href="{% url 'books:show' id=review.book.id %}">{{review.book.book_title}}</a></li></h4>
          {% endfor %}
        </ul>
      </div>
    </div>
  </body>
</html>